// Generated by Xata Codegen 0.23.5. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "reviews",
    columns: [
      { name: "name", type: "string" },
      { name: "review", type: "text" },
      { name: "image", type: "string" },
      { name: "paket_wisata", type: "string" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Reviews = InferredTypes["reviews"];
export type ReviewsRecord = Reviews & XataRecord;

export type DatabaseSchema = {
  reviews: ReviewsRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://poptour-id-s-workspace-u7gmbh.us-east-1.xata.sh/db/poptour",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
